name: ETL Refresh

on:
  schedule:
    - cron: '0 0 * * *'
    workflow_dispatch: 
jobs: 
  etl_refresh:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
      uses: actions/checkout@v4

      - name: set up python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.10'
      
      - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
      - name: Create data directory
      run: mkdir -p data

      - name: Run ETL
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: python src/etl.py
      
      # Option 1: Commit DB back to repo (simplest for now, for demo)
      - name: Commit and push database
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/macro_data.db
          # Only commit if there are changes
          git diff --staged --quiet || git commit -m "Automated DB refresh via GitHub Actions"
          git push